### ISSUE TITLE
Inclusion in CMasher docs

### ISSUE THREAD

**Issue by 1313e** [rdzudzar/Tableau_Colormaps#1]
Lovely to see others using CMasher in other applications than just pure Python.
Do you think that this would be a good addition to the online docs for CMasher on how to use its colormaps in other applications/languages?

**Comment by rdzudzar** [comment]
Making them available in multiple packages can be useful, especially if the setup is not complicated: from your side to make it and from users side to use it. To add - so far I haven't seen anyone (on the public Tableau gallery) using colormaps that are not in Tableau by default (except myself) :/

**Comment by 1313e** [comment]
Well, I was mostly thinking that if people would want to use CMasher in something, the first place they would look is probably the CMasher documentation.
So, we could write this repo up nicely to include it in the CMasher docs. :)

**Comment by rdzudzar** [comment]
Sure, I'm up for that! :)

**Comment by rdzudzar** [comment]
Moved instruction here: https://github.com/1313e/CMasher/issues/36
